In [2]:
import pandas as pd
import numpy as np
from faker import Faker
from datetime import datetime as dt

Set parameters for the company size and date ranges:

In [ ]:
n_employees = 100
n_projects = 40
n_clients = 15
n_weeks = 24
start_date = dt(2025, 1, 1)
end_date = dt(2026, 12, 31)
bench = 0.15 
working_hours = 8

In [4]:
job_matrix_df = pd.DataFrame(
    {
            "Role": ["Project Manager", "Business Analyst", "Software Engineer", "Tester", "Solution Architect", "DevOps Engineer", "Platform Engineer", "Cloud Engineer"],
            "Cost_Rate": [55, 50, 75, 45, 100, 60, 55, 30]
    }
)

job_matrix_df

                 Role  Cost_Rate
0     Project Manager         55
1    Business Analyst         50
2   Software Engineer         75
3              Tester         45
4  Solution Architect        100
5     DevOps Engineer         60
6   Platform Engineer         55
7      Cloud Engineer         30

In [5]:
#Define the department dataset
department_df = pd.DataFrame(
            {
            "Department_ID": ["D01", "D02", "D03", "D04"],
            "Department_Name": ["Energy", "Finance", "Healthcare", "Retail"],}
        )
department_df

  Department_ID Department_Name
0           D01          Energy
1           D02         Finance
2           D03      Healthcare
3           D04          Retail

In [6]:
#Define the resource dataset

rng = np.random.default_rng(42)
fake = Faker()
fake.seed_instance(42)

resource_df = pd.DataFrame(
        {
        "Employee_ID": [f"E{i}" for i in range(1, n_employees + 1)],
        "Department_ID": rng.choice(department_df["Department_ID"], n_employees),
        "Role": rng.choice(job_matrix_df["Role"], n_employees),
        "Level": rng.choice([1, 2, 3], n_employees),
        "Name": [fake.name() for _ in range(n_employees)]
        }
    )

resource_df

   Employee_ID Department_ID               Role  Level              Name
0           E1           D01  Platform Engineer      2      Allison Hill
1           E2           D04   Business Analyst      3       Noah Rhodes
2           E3           D03  Platform Engineer      2   Angie Henderson
3           E4           D02    Project Manager      3     Daniel Wagner
4           E5           D02  Platform Engineer      2   Cristian Santos
..         ...           ...                ...    ...               ...
95         E96           D02    Project Manager      2    Anna Henderson
96         E97           D01  Software Engineer      3        Aaron Wise
97         E98           D03    Project Manager      2  Deborah Figueroa
98         E99           D03  Software Engineer      1     Jessica Smith
99        E100           D01     Cloud Engineer      1     Stephen Mckee

[100 rows x 5 columns]

In [7]:
#Define the project dataset
project_df = pd.DataFrame(
        {
        "Project_ID" : [f"P{i}" for i in range(1, n_projects + 1)],
        "Project_Name": [fake.bs().title() for _ in range(n_projects)],
        "Project_Type": rng.choice(["Fixed Price", "T&M"], n_projects),
        "Client ID": rng.choice([f"C{i}" for i in range(1, n_clients + 1)], n_projects),
        "Department_ID": rng.choice(department_df["Department_ID"], n_projects),
        "Start_Date": [fake.date_between(start_date, end_date) for _ in range(n_projects)],
        "Duration": rng.choice([3, 6, 9, 12, 18, 24], n_projects),
        "Project_Manager_ID": rng.choice(resource_df[resource_df["Role"] == "Project Manager"]["Employee_ID"], n_projects),
        "Contract Value": [fake.pydecimal(left_digits=6, right_digits=2, positive=True) for _ in range(n_projects)]}
    )

project_df

,Project_ID,Project_Name,Project_Type,Client ID,Department_ID,Start_Date,Duration,Project_Manager_ID,Contract Value
0,P1,Incubate Robust Relationships,Fixed Price,C10,D01,2025-08-11,24,E71,356736.79
1,P2,Benchmark B2B E-Commerce,T&M,C5,D04,2025-06-13,18,E17,991014.17
2,P3,Enable Revolutionary Content,Fixed Price,C10,D04,2025-11-30,18,E71,534572.93
3,P4,Disintermediate Revolutionary Convergence,T&M,C8,D01,2026-09-03,12,E38,853240.67
4,P5,Architect Interactive Web Services,T&M,C14,D01,2026-03-27,9,E4,519066.32
5,P6,Transform Synergistic Schemas,Fixed Price,C4,D01,2026-04-17,6,E98,787926.01
6,P7,Matrix Transparent E-Business,Fixed Price,C15,D01,2026-05-24,24,E20,916232.63
7,P8,Extend B2C Action-Items,T&M,C15,D04,2025-09-08,18,E50,284430.87
8,P9,Cultivate Granular Roi,Fixed Price,C3,D04,2025-12-28,3,E20,152657.83
9,P10,Matrix Transparent Web-Readiness,Fixed Price,C3,D01,2025-12-10,18,E98,989545.17
10,P11,Reinvent Open-Source E-Markets,T&M,C8,D03,2025-12-10,3,E71,239816.78
11,P12,Exploit Interactive Niches,T&M,C1,D01,2026-06-09,18,E72,686075.95
12,P13,Leverage Sticky Architectures,Fixed Price,C5,D02,2025-06-15,18,E38,891937.79
13,P14,Cultivate Robust Info-Mediaries,Fixed Price,C7,D03,2026-02-02,3,E47,954596.86
14,P15,Enhance 24/365 Bandwidth,Fixed Price,C15,D03,2026-01-03,9,E70,970914.87
15,P16,Seize Extensible E-Services,T&M,C15,D04,2026-09-09,3,E72,266889.77
16,P17,Enhance Proactive Web Services,T&M,C3,D01,2026-12-01,12,E96,371782.34
17,P18,Aggregate Wireless Supply-Chains,T&M,C14,D01,2026-09-11,24,E4,903013.87
18,P19,Empower Innovative Niches,T&M,C2,D02,2026-07-26,3,E70,757193.34
19,P20,Seize Wireless Methodologies,T&M,C12,D02,2025-05-12,9,E17,561239.14
20,P21,E-Enable Open-Source Web-Readiness,Fixed Price,C13,D04,2026-05-27,24,E27,345884.45
21,P22,Embrace Back-End Roi,Fixed Price,C14,D04,2025-03-07,6,E72,435239.81
22,P23,Benchmark Back-End Paradigms,T&M,C4,D02,2025-08-09,3,E27,245095.23
23,P24,Transform User-Centric Convergence,T&M,C14,D04,2026-02-05,9,E72,501641.23
24,P25,Drive Turn-Key E-Commerce,T&M,C2,D02,2026-05-31,12,E47,167348.66
25,P26,Expedite One-To-One Architectures,Fixed Price,C8,D03,2026-05-07,12,E27,446954.87
26,P27,Productize Dynamic Portals,Fixed Price,C8,D02,2026-04-26,6,E33,535970.03
27,P28,Integrate User-Centric Synergies,Fixed Price,C5,D01,2025-09-18,24,E47,973349.66
28,P29,Mesh 24/365 Relationships,Fixed Price,C1,D04,2025-03-14,12,E71,907189.90
29,P30,Brand Innovative Web Services,T&M,C12,D01,2026-09-28,6,E50,998348.96
30,P31,Redefine Open-Source E-Business,T&M,C6,D01,2026-08-07,24,E98,600149.05
31,P32,Harness 24/7 Content,Fixed Price,C10,D01,2025-07-02,24,E96,413118.66
32,P33,Deliver Extensible Web Services,Fixed Price,C7,D02,2026-06-07,9,E71,664365.89
33,P34,Deploy World-Class Interfaces,T&M,C6,D01,2025-08-30,3,E50,331251.73
34,P35,Scale Distributed Schemas,Fixed Price,C14,D01,2025-06-24,12,E27,386193.67
35,P36,Enable Dynamic E-Markets,T&M,C2,D03,2026-09-19,12,E38,130434.65
36,P37,Repurpose Enterprise Methodologies,T&M,C12,D04,2025-06-04,3,E17,801364.62
37,P38,Extend Virtual E-Business,Fixed Price,C12,D01,2025-04-25,12,E33,981334.72
38,P39,Maximize Seamless Interfaces,Fixed Price,C6,D02,2025-01-19,24,E98,752483.80
39,P40,Engage Clicks-And-Mortar Content,T&M,C4,D03,2025-02-05,3,E38,513160.99

In [ ]:
#Assign people to projects, based on bench parameter, assumed 100% utilised and 1 project per employee
assignment_df = pd.DataFrame(
        {
        "Project_ID": rng.choice(project_df["Project_ID"], int(n_employees*(1 - bench))),
        "Employee_ID": rng.choice(resource_df["Employee_ID"], int(n_employees*(1 - bench)), replace=False),
        "Assignment_Start_Date": [fake.date_between(start_date, end_date) for _ in range(int(n_employees*(1 - bench)))],
        "Assignment_End_Date": }
    )

assignment_df

   Project_ID Employee_ID Assignment_Start_Date Assignment_End_Date
0         P30         E93            2026-11-05          2026-10-23
1         P24         E71            2025-12-25          2026-10-23
2          P3         E39            2025-05-22          2026-10-23
3         P16         E78            2025-02-09          2026-10-23
4         P20         E59            2025-07-22          2026-10-23
..        ...         ...                   ...                 ...
80        P11         E23            2025-07-08          2026-10-23
81        P32         E74            2025-03-21          2026-10-23
82        P19         E87            2026-06-26          2026-10-23
83         P8         E38            2026-08-24          2026-10-23
84         P7         E58            2025-08-23          2026-10-23

[85 rows x 4 columns]

In [ ]:
#Define the timesheet dataset

timesheet_df = pd.DataFrame(
        {
        "Employee_ID": [],
        "Project_ID": [],
        "Period_Start_Date": [],
        "Billable_Hours": [],
        "Internal_Hours": []}
    )

project_df