In [16]:
import pandas as pd
import numpy as np
from faker import Faker
from datetime import datetime as dt

Set parameters for the company size and date ranges:

In [ ]:
n_employees = 100
n_projects = 40
n_clients = 15
start_date = dt(2025, 1, 1)
end_date = dt(2026, 12, 31)
bench = 0.15 
working_hours = 8

In [18]:
job_matrix_df = pd.DataFrame(
    {
            "Role": ["Project Manager", "Business Analyst", "Software Engineer", "Tester", "Solution Architect", "DevOps Engineer", "Platform Engineer", "Cloud Engineer"],
            "Cost_Rate": [55, 50, 75, 45, 100, 60, 55, 30]
    }
)

job_matrix_df

                 Role  Cost_Rate
0     Project Manager         55
1    Business Analyst         50
2   Software Engineer         75
3              Tester         45
4  Solution Architect        100
5     DevOps Engineer         60
6   Platform Engineer         55
7      Cloud Engineer         30

In [19]:
#Define the department dataset
department_df = pd.DataFrame(
            {
            "Department_ID": ["D01", "D02", "D03", "D04"],
            "Department_Name": ["Energy", "Finance", "Healthcare", "Retail"],}
        )
department_df

  Department_ID Department_Name
0           D01          Energy
1           D02         Finance
2           D03      Healthcare
3           D04          Retail

In [ ]:
#Define the resource dataset

rng = np.random.default_rng(42)
fake = Faker()
fake.seed_instance(43)

resource_df = pd.DataFrame(
        {
        "Employee_ID": [f"E{i}" for i in range(1, n_employees + 1)],
        "Department_ID": rng.choice(department_df["Department_ID"], n_employees),
        "Role": rng.choice(job_matrix_df["Role"], n_employees),
        "Level": rng.choice([1, 2, 3], n_employees),
        "Name": [fake.name() for _ in range(n_employees)]
        }
    )

resource_df

   Employee_ID Department_ID               Role  Level               Name
0           E1           D01  Platform Engineer      2   Michael Whitaker
1           E2           D04   Business Analyst      3    Courtney Torres
2           E3           D03  Platform Engineer      2    Mr. James Baker
3           E4           D02    Project Manager      3     Edward Jackson
4           E5           D02  Platform Engineer      2      David Shepard
..         ...           ...                ...    ...                ...
95         E96           D02    Project Manager      2        Mary Keller
96         E97           D01  Software Engineer      3    Justin Petersen
97         E98           D03    Project Manager      2         Ellen Moon
98         E99           D03  Software Engineer      1    Matthew Schultz
99        E100           D01     Cloud Engineer      1  Vanessa Mccormick

[100 rows x 5 columns]

In [31]:
#Define the project dataset
project_df = pd.DataFrame(
        {
        "Project_ID" : [f"P{i}" for i in range(1, n_projects + 1)],
        "Project_Name": [fake.bs().title() for _ in range(n_projects)],
        "Project_Type": rng.choice(["Fixed Price", "T&M"], n_projects),
        "Client ID": rng.choice([f"C{i}" for i in range(1, n_clients + 1)], n_projects),
        "Department_ID": rng.choice(department_df["Department_ID"], n_projects),
        "Start_Date": [fake.date_between(start_date, end_date) for _ in range(n_projects)],
        "Duration": rng.choice([3, 6, 9, 12, 18, 24], n_projects),
        "Project_Manager_ID": rng.choice(resource_df[resource_df["Role"] == "Project Manager"]["Employee_ID"], n_projects),
        "Contract Value": [fake.pydecimal(left_digits=6, right_digits=2, positive=True) for _ in range(n_projects)]}
    )

project_df

,Project_ID,Project_Name,Project_Type,Client ID,Department_ID,Start_Date,Duration,Project_Manager_ID,Contract Value
0,P1,Benchmark B2C Bandwidth,Fixed Price,C12,D03,2026-03-02,3,E70,749272.29
1,P2,Expedite Frictionless E-Tailers,T&M,C5,D03,2026-04-24,6,E70,406969.85
2,P3,Enhance Real-Time Networks,Fixed Price,C13,D03,2026-01-08,24,E4,498907.90
3,P4,Benchmark Enterprise Systems,T&M,C6,D01,2026-05-11,3,E71,815766.71
4,P5,Disintermediate Sticky Vortals,T&M,C13,D02,2026-03-22,9,E70,629326.12
5,P6,Enhance Extensible Info-Mediaries,T&M,C7,D01,2025-01-24,3,E72,726400.69
6,P7,Transition Real-Time Platforms,Fixed Price,C2,D02,2025-06-18,3,E72,755978.86
7,P8,Evolve Efficient Methodologies,T&M,C12,D01,2025-02-10,24,E20,724610.16
8,P9,Extend Cross-Platform Models,T&M,C1,D01,2026-09-15,3,E20,834010.42
9,P10,Grow Proactive Info-Mediaries,T&M,C12,D04,2026-09-09,6,E98,491923.57
10,P11,Leverage Impactful E-Business,Fixed Price,C1,D01,2026-11-06,24,E47,995370.46
11,P12,Incentivize Cross-Platform Supply-Chains,T&M,C4,D04,2025-03-14,12,E38,361482.54
12,P13,Streamline B2B E-Business,T&M,C10,D01,2026-05-10,3,E27,184437.58
13,P14,E-Enable Transparent Vortals,Fixed Price,C15,D04,2026-10-02,9,E70,791617.19
14,P15,Optimize Dot-Com Partnerships,Fixed Price,C7,D02,2025-07-12,24,E71,365552.70
15,P16,Integrate Plug-And-Play Paradigms,Fixed Price,C2,D03,2026-10-21,9,E4,239281.79
16,P17,Deliver Cutting-Edge Supply-Chains,T&M,C4,D02,2026-08-06,12,E50,364002.39
17,P18,Engage Killer Applications,Fixed Price,C14,D02,2026-06-23,12,E98,965867.85
18,P19,Seize Mission-Critical Convergence,Fixed Price,C11,D02,2025-04-06,12,E27,635094.20
19,P20,Enhance Mission-Critical E-Business,T&M,C2,D03,2025-04-16,6,E27,474941.14
20,P21,Monetize Cross-Media E-Services,Fixed Price,C6,D02,2026-07-18,24,E96,262755.09
21,P22,Iterate Proactive Users,Fixed Price,C4,D03,2025-09-11,24,E4,701817.48
22,P23,Leverage Back-End Infrastructures,T&M,C3,D04,2025-05-20,3,E38,676835.66
23,P24,Innovate Enterprise Paradigms,T&M,C13,D02,2026-06-15,18,E38,436995.97
24,P25,Integrate Killer Channels,T&M,C10,D02,2025-02-08,18,E72,164745.18
25,P26,Incubate Dot-Com Channels,T&M,C3,D01,2025-06-28,18,E17,532116.65
26,P27,Incubate Killer Niches,Fixed Price,C10,D02,2026-04-15,9,E38,674446.99
27,P28,Syndicate 24/365 Communities,T&M,C7,D01,2026-10-09,9,E17,340102.07
28,P29,Mesh B2C Relationships,T&M,C1,D01,2025-06-25,24,E72,756033.00
29,P30,Seize Cross-Platform Architectures,Fixed Price,C7,D04,2025-01-24,3,E70,485051.13
30,P31,Drive Turn-Key E-Business,Fixed Price,C3,D01,2025-08-26,18,E47,783626.83
31,P32,Target One-To-One Technologies,Fixed Price,C4,D02,2026-07-31,24,E38,605944.79
32,P33,Generate Intuitive Web Services,Fixed Price,C14,D04,2025-12-30,18,E17,657420.86
33,P34,Grow Customized Platforms,Fixed Price,C11,D04,2026-02-09,9,E96,208649.38
34,P35,Innovate Holistic Eyeballs,Fixed Price,C3,D01,2025-06-27,12,E70,742861.00
35,P36,Integrate Efficient Roi,T&M,C13,D01,2026-08-11,3,E33,812546.38
36,P37,Synthesize Visionary Solutions,Fixed Price,C9,D02,2026-04-01,24,E38,405564.14
37,P38,Enhance Scalable Markets,T&M,C14,D03,2026-12-10,9,E71,746277.34
38,P39,Whiteboard Clicks-And-Mortar Synergies,T&M,C12,D04,2026-01-02,3,E71,332695.44
39,P40,Empower Collaborative Relationships,T&M,C6,D01,2025-12-17,18,E38,493509.61

In [ ]:
#Define the assignment dataset
assignment_df = pd.DataFrame(
        {
        "Project_ID": [],
        "Employee_ID": [],
        "Assignment_Start_Date": [],
        "Assignment_End_Date": [],
        "Allocation_Percent": []}
    )

In [ ]:
#Define the timesheet dataset

timesheet_df = pd.DataFrame(
        {
        "Employee_ID": [],
        "Project_ID": [],
        "Period_Start_Date": [],
        "Billable_Hours": [],
        "Internal_Hours": []}
    )

project_df